title: gyutae.dev
description: 개발, 생각, 그리고 배운 것들을 기록합니다.
url: "https://gyutaetae.github.io"
baseurl: ""

author:
  name: gyutae
  github: gyutaetae

permalink: /posts/:slug/

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - tools/
  - README.md
  - LICENSE
  - .devcontainer/
  - .github/
